name: Docker-Image-CI

on: [push]

env:
  IMAGE_NAME: go-app-k8s


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Log into registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME
        docker push $IMAGE_ID:latest
